### ISSUE TITLE
[BUG]: Unable to create remote user

### ISSUE THREAD

**Issue by CyberAustin** [syngit-org/syngit#106]
### Describe the bug

When following the instructions in "Usage", I get the following error:

```Error from server: error when creating "remote-user.yml": admission webhook "vremoteusers-association.v1beta3.syngit.io" denied the request: RemoteUserBinding.syngit.io "associated-rub-system:admin" is invalid: [metadata.name: Invalid value: "associated-rub-system:admin": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "system:admin": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]```

### To Reproduce

```
apiVersion: v1
kind: Secret
metadata:
  name: github.com-cyberaustin-auth
type: kubernetes.io/basic-auth
stringData:
  username: cyberaustin
  password:  [redacted]

apiVersion: syngit.io/v1beta3
kind: RemoteUser
metadata:
    name: github-cyberaustin
    annotations:
      syngit.io/remoteuserbinding.managed: "true"
spec:
  gitBaseDomainFQDN: "github.com"
  email: [redacted]
  secretRef:
        name: github.com-cyberaustin-auth
```

### Expected behavior

Success?

### System infos

- syngit version: 0.4.4
- image: ghcr.io/syngit-org/syngit-provider-github:v0.1.0

logs:

```
2025-04-11T14:05:21Z    INFO    setup   starting manager
2025-04-11T14:05:21Z    INFO    controller-runtime.metrics      Starting metrics server
2025-04-11T14:05:21Z    INFO    setup   disabling http/2
2025-04-11T14:05:21Z    INFO    starting server {"name": "health probe", "addr": "[::]:8081"}
I0411 14:05:21.550782       1 leaderelection.go:254] attempting to acquire leader lease syngit/a969d404.io...
I0411 14:05:21.574975       1 leaderelection.go:268] successfully acquired lease syngit/a969d404.io
2025-04-11T14:05:21Z    DEBUG   events  syngit-provider-github-55778fb5-fcj6c_56270cc7-8d1b-49ca-b5c0-09b24b4e51f7 became leader        {"type": "Normal", "object": {"kind":"Lease","namespace":"syngit","name":"a969d404.io","uid":"8c44b792-1cd2-4ac2-bf01-46f745f56023","apiVersion":"coordination.k8s.io/v1","resourceVersion":"34583412"}, "reason": "LeaderElection"}
2025-04-11T14:05:21Z    INFO    Starting EventSource    {"controller": "remoteuser", "controllerGroup": "syngit.io", "controllerKind": "RemoteUser", "source": "kind source: *v1beta2.RemoteUser"}
2025-04-11T14:05:21Z    INFO    Starting EventSource    {"controller": "remoteuser", "controllerGroup": "syngit.io", "controllerKind": "RemoteUser", "source": "kind source: *v1.Secret"}
2025-04-11T14:05:21Z    INFO    Starting Controller     {"controller": "remoteuser", "controllerGroup": "syngit.io", "controllerKind": "RemoteUser"}
2025-04-11T14:05:21Z    INFO    Starting workers        {"controller": "remoteuser", "controllerGroup": "syngit.io", "controllerKind": "RemoteUser", "worker count": 1}
2025-04-11T14:05:21Z    INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": ":8443", "secure": true}
```

### Additional context

It's entirely possible I'm doing something wrong.

**Comment by damsien** [comment]
Hello @CyberAustin thanks for raising this one, I'm working on it!

**Comment by CyberAustin** [comment]
Anything else I can try?

**Comment by damsien** [comment]
@CyberAustin To explain a little bit what happened, it does not work because you use a special user containing the `:` character (`system:admin`). For now, we never found someone using the operator with the `system:admin` user. I'm working on it rn.
If you still want to use the operator with the version 0.4.4, please try to use an user that have an username that respect the `'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'` regex.

**Comment by CyberAustin** [comment]
This is just the default kube-config.yml that k3s generated. I'll look into making a new user.

**Comment by damsien** [comment]
Hello @CyberAustin, you can try the latest release ([v0.4.5](https://github.com/syngit-org/syngit/releases/tag/v0.4.5)), it should fix the bug. Waiting for you response before closing the issue.

Do not hesitate to raise another issue if you have any problem!

**Comment by CyberAustin** [comment]
Got another error creating the remote-syncer

```
Error from server: error when creating "remote-syncer.yml": admission webhook "vremotesyncers-target-pattern.v1beta3.syngit.io" denied the request: RemoteTarget.syngit.io "rt-CyberAustin-kube-backup-main-CyberAustin-kube-backup-main" is invalid: metadata.name: Invalid value: "rt-CyberAustin-kube-backup-main-CyberAustin-kube-backup-main": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

This wasn't a big deal, as I just changed it all to lower case in the `remoteRepository`, but I don't see why it MUST be all lowercase.

**Comment by damsien** [comment]
Because it auto-generate a `RemoteTarget` object using the repository as an unique identifier. Therefore the name of the auto-generated `RemoteTarget` contains the repository name. I'm on it to convert it as lowercase by default.

Did you had any other problem?

**Comment by CyberAustin** [comment]
I can't get it to sync everything. But I think that's something I'm doing
wrong, not a bug or anything

**Comment by damsien** [comment]
Don't hesitate to tell me!

**Comment by CyberAustin** [comment]
what do I put for `resources:` to get it to sync everything? `[""] ["*"] ["all"]` is failing me

**Comment by damsien** [comment]
Here is the way to scope everything:
```yaml
scopedResources:
    rules:
    - apiGroups:
      - '*'
      apiVersions:
      - '*'
      resources:
      - '*'
      operations:
      - whatever you want
```

but ⚠ WARNING ⚠  it will scope EVERYTHING in your namespace including the `RemoteSyncer` itself. So you will not be able to delete it! Please **avoid this configuration** if you can. Also, for now, it is not possible to scope cluster-wide resources using Syngit.

I highly recommend you to only scope the k8s native `apiGroups` and add the ones that the operators installed on your cluster provide:
```yaml
scopedResources:
    rules:
    - apiGroups:
      - ""
      - apps
      - batch
      - autoscaling
      - coordination.k8s.io
      - events.k8s.io
      apiVersions:
      - '*'
      resources:
      - '*'
      operations:
      - whatever you want
```
