### ISSUE TITLE
[FE]: RemoteSyncer validate webhook RBAC checker

### ISSUE THREAD

**Issue by damsien** [syngit-org/syngit#27]
[Roadmap: v0.2 - 2024/12](https://github.com/syngit-org/syngit/wiki/%F0%9F%93%9C-Roadmap#v02---202412) RemoteSyncer validating webhook RBAC checker
As the DevOps of my team, I want the creation of my RemoteSyncer to be blocked if I am not permitted to scope the resources.

## What to do

Register a new custom webhook in the [main.go](https://github.com/syngit-org/syngit/blob/main/cmd/main.go) file:
```yaml
mgr.GetWebhookServer().Register("/syngit-v1beta2-remotesyncer-rbac-checker", &webhook.Admission{Handler: &controller.RemoteSyncerRBACCheckerWebhookHandler{
      Client:  mgr.GetClient(),
      Decoder: admission.NewDecoder(mgr.GetScheme()),
  }})
```

Create a new `internal/controller/remotesyncer_rbac_checker_webhook.go` file. Instantiate the handler like the [remoteuser_association_webhook.go](https://github.com/syngit-org/syngit/blob/main/internal/controller/reconcile_remoteuser_owner.go).

Check for the `CREATE` and `UPDATE` operation/
```yaml
if string(req.Operation) == "CREATE"
```
```yaml
if string(req.Operation) == "UPDATE"
```

In the `Handle()` function:
1. Get the user from the AdmissionRequest: `req.DeepCopy().UserInfo.Username`.
2. Retrieve the `rules` from the `scopedResources` field: `rswh.Decoder.DecodeRaw(req.OldObject, rs)`.
3. Use the `SubjectAccessReview` in order to check if the user has the rights to instantiate the RemoteSyncer's rules.

## Additional context

If you have any questions, please tag @damsien.
