### ISSUE TITLE
[FE]: Add helm dependency to cert-manager

### ISSUE THREAD

**Issue by damsien** [syngit-org/syngit#44]
[Roadmap 2025/05](https://github.com/syngit-org/syngit/wiki/%F0%9F%93%9C-Roadmap#202505) Add helm dependency to cert-manager
As the DevOps of my team, I want to be able to directly build the appropriate final chart to install Syngit on a blank cluster (a new KinD cluster for instance).

## What to do

Go to the latest [chart version listed](https://github.com/syngit-org/syngit/tree/main/charts). In the [Chart.yaml](https://github.com/syngit-org/syngit/tree/main/charts/0.4.0/Chart.yaml), add the following lines:

```yaml
  - name: cert-manager
    condition: webhook.certmanager.enable
    repository: https://charts.jetstack.io --force-update
    version: ~v1.16
```

## Additional context

If you have any questions, please tag @damsien.
