### ISSUE TITLE
[FE]: Default `excludedFields` ConfigMaps

### ISSUE THREAD

**Issue by damsien** [syngit-org/syngit#47]
[Roadmap 2025/01](https://github.com/syngit-org/syngit/wiki/%F0%9F%93%9C-Roadmap#202501) Default `excludedFields` ConfigMaps.
As the Platform Engineer of my team, I want to set defaults `excludedFields` ConfigMaps that will be applied for all of the `RemoteSyncers` of the cluster.

#### 1. Check for the env var

In the [`convertToYaml()`](https://github.com/syngit-org/syngit/blob/main/internal/interceptor/webhook_request_checker.go#L357) function, add some lines that check for all configmaps in the namespace where Syngit is installed (`os.Getenv("MANAGER_NAMESPACE")`) which has the `syngit.io/cluster-default-excluded-fields: "true"` label (using `wrc.k8sClient`).

#### 2. Move the excludedFields remover block into a function

Move the following block into a function because it will be used twice. 1. For the `remoteSyncer.Spec.ExcludedFieldsConfigMapRef` (is specified) & 2. For the default excluded fields (if some exist).

https://github.com/syngit-org/syngit/blob/8442bb1cd927946fe6e9b0c3e2c294e69ff3b9c7/internal/controller/webhook_request_checker.go#L376-L397

The function signature:
```go
func (wrc *WebhookRequestChecker) getPathsFromConfigMap(remoteSyncer syngit.RemoteSyncer) paths []string {}
```

The function call:
```go
paths = append(paths, wrc.getPathsFromConfigMap(wrc.remoteSyncer)...)
```

In the function, search for the key `excludedFields` in the ConfigMap..

#### 3. Check for the excluded fields

For each ConfigMaps (with the correct label) retrieved, call the function.

#### 4. Update the chart

Go to the latest chart version https://github.com/syngit-org/syngit/tree/main/charts. Create a `config` folder and create the ConfigMap.
```yaml
{{- if eq .config.webhook.defaultExcludedFields.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-excluded-fields
  namespace: {{ .Release.Namespace }}
  labels:
    syngit.io/cluster-default-excluded-fields: "true"
data:
  excludedFields: |
    - metadata.annotations.[kubectl.kubernetes.io/last-applied-configuration]
    - metadata.creationTimestamp
    - metadata.generateName
    - metadata.generation
    - metadata.managedFields
    - metadata.resourceVersion
    - metadata.uid
    - status
{{- end }}
```

Add a `.config.defaultExcludedFields.enabled: true` to the `values.yaml`.

## Additional context

If you have any questions, please tag @damsien.
