### ISSUE TITLE
[BUG]: `excludedFields` are not recursives

### ISSUE THREAD

**Issue by damsien** [syngit-org/syngit#95]
### Describe the bug

Considering this object:
```yaml
kind: MyObject
...
spec:
  field1: "test"
  field2: "test"
...
```

Currently, in the `RemoteSyncer`, this configuration will not exclude anything:
```yaml
apiVersion: syngit.io/v1beta3
kind: RemoteSyncer
...
spec:
  excludedFields:
    - spec
```

While this one will exclude the fields:
```yaml
apiVersion: syngit.io/v1beta3
kind: RemoteSyncer
...
spec:
  excludedFields:
    - spec.field1
    - spec.field2
```

We want the first configuration to exclude the `spec.field1` and `spec.field2` as well.

### To Reproduce

1. Create a Kubernetes resource
2. Try to exclude a "non-final" field of this resource. In other words, a field that contains other fields

### Expected behavior

It should exclude all sub-fields of the "non-final" field.

### System infos

- Syngit version: 0.4.1
- RemoteSyncer `apiVersion`: v1beta3

### How to solve this issue

Change this function:
https://github.com/syngit-org/syngit/blob/8908e43ebd78c6004afafe8699ef8b8f8e5c6272/pkg/utils/parser.go#L35

When taking this path as input: `spec`, it should excluded `spec.field1` AND `spec.field2`.
